Device:
  Port: COM5
  Baudrate: 1000000
  ProtocolVersion: 2.0
Joint:
  Number: 4
  Joint_00:
    index: 11
    a: 0
    alpha: -90
    b: 0
    beta: 0
    d: 76.5
    theta: 0
    p_gain: 200
    i_gain: 1
    d_gain: 2000
    max_rpm: 100
    max_acc: 1
    max_LoadmA: 0.5
    min_ang: 10
    max_ang: 350
    inposition: 0.01
    offset_angle: 180
  Joint_01:
    index: 12
    a: 530
    alpha: 0
    b: 24
    beta: 0
    d: 0
    theta: -90
    p_gain: 200
    i_gain: 1
    d_gain: 2000
    max_rpm: 100
    max_acc: 1
    max_LoadmA: 0.5
    min_ang: 10
    max_ang: 350
    inposition: 0.01
    offset_angle: 180
  Joint_02:
    index: 13
    a: 474
    alpha: 0
    b: -24
    beta: 0
    d: 0
    theta: 90
    p_gain: 200
    i_gain: 1
    d_gain: 2000
    max_rpm: 100
    max_acc: 1
    max_LoadmA: 0.5
    min_ang: 10
    max_ang: 350
    inposition: 0.01
    offset_angle: 180
  Joint_03:
    index: 14
    a: 96
    alpha: 0
    b: 0
    beta: 0
    d: 0
    theta: 0
    p_gain: 200
    i_gain: 1
    d_gain: 2000
    max_rpm: 100
    max_acc: 1
    max_LoadmA: 0.5
    min_ang: 10
    max_ang: 350
    inposition: 0.01
    offset_angle: 180
