init_position:
  joint_0: 180.0
  joint_1: 268.0
  joint_2: 92.0
  joint_3: 359.0
safety_position:
  joint_0: 180.0
  joint_1: 180.0
  joint_2: 100.0
  joint_3: 238.0
target_position:
  x: 510.0
  y: -100.0
  z: 300.0
wait_position:
  x: 500.0
  y: -100.0
  z: 300.0
